language: node_js
node_js:
  - 12
service:
  - redis-server
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    # all_branches: true
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
